apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: helloworld-prod-imagestream
  namespace: multi-cloud
spec:
  lookupPolicy:
    local: true
  tags:
  - name: "production"
    from:
      kind: DockerImage
      name: "registry.gitlab.com/gitlab-com/partners/alliance/ibm-red-hat/sandbox/customer-k/multi-cloud-demo/main:latest"
    importPolicy: {scheduled: true}
    referencePolicy:
      type: Source
