FROM tomcat:latest

ENV HOSTNAME=my-container \
    ENV=production \
    CLUSTER=m12t68-90tg3 \
    PLATFORM=local \
    OCP_VERSION=4.10

ADD target/demo.war /usr/local/tomcat/webapps/

EXPOSE 8080

CMD ["catalina.sh", "run"]