apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tomcat-multicloud
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: multicloud-placement
      requeueAfterSeconds: 180
  template:
    metadata:
      name: '{{name}}-tomcat'
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/purefield/multi-cloud-demo.git
        targetRevision: argocd
        path: multi-cloud-argo/app/tomcat-demo
      destination:
        server: https://kubernetes.default.svc
        namespace: tomcat-demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
