---
kind: ConfigMap
apiVersion: v1
metadata:
  name: acm-placement
  namespace: openshift-gitops
data:
  apiVersion: cluster.open-cluster-management.io/v1beta1
  kind: placementdecisions
  matchKey: clusterName
  statusListKey: decisions
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: acm-placementrule
  namespace: openshift-gitops
data:
  apiVersion: apps.open-cluster-management.io/v1
  kind: placementrules
  matchKey: clusterName
  statusListKey: decisions
